//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatEatToday.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public int Id { get; set; }
        public int Shop_Id { get; set; }
        public string Cus_Id { get; set; }
        public Nullable<float> Rating { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
