//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatEatToday.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Menu
    {
        [Display(Name = "Menu")]
        public int menu_id { get; set; }
        [Display(Name = "Shop")]
        public int shop_id { get; set; }
        [Display(Name = "Menu Name")]
        public string menu_name { get; set; }
        [Display(Name = "Comment")]
        public string comment { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
