//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatEatToday.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public int owner_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string token { get; set; }
        public int shop_id { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
