//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatEatToday.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.Menus = new HashSet<Menu>();
            this.Owners = new HashSet<Owner>();
        }
    
        [Display(Name = "Shop ID")]
        public int shop_id { get; set; }

        [Display(Name = "Name")]
        public string name { get; set; }
        [Display(Name = "Shop Details")]
        public string details { get; set; }
        [Display(Name = "Shop Type")]
        public string type { get; set; }
        [Display(Name = "Shop Picture")]
        public string pic { get; set; }
        [Display(Name = "Shop Location (Latitude)")]
        public string latitude { get; set; }
        [Display(Name = "Shop Location (Longitude)")]
        public string longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Owner> Owners { get; set; }
    }
}
